### ISSUE TITLE
CLIP version reported in Table-4

### ISSUE THREAD

**Issue by slymane** [noagarcia/phase#1]
Hi folks, thanks for this great dataset! I'm trying to reimplement some of your tests but am getting different results for Table-4. Can you share which version of CLIP you're using? I'm noticing some significant differences based on model choice when trying varying ones from [OpenClip](https://github.com/mlfoundations/open_clip).

**Comment by yankungou** [comment]
Hi slymane, thank you for your interest on our work. We are using `ViT-B/32` CLIP model from [CLIP](https://github.com/openai/CLIP).
